version: '3'
name: otaku-bot
services:
  api:
    container_name: otaku-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    expose:
      - '4000'
